/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logic.controller.DatosController;
import logic.controller.DatosLogic;
import logic.model.AdministradorModel;
import logic.model.PersonaModel;

/**
 *
 * @author CarlosDelrio
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("LOGIN PANEL");
        this.setIconImage(new ImageIcon(getClass() .getResource("/icons_images/icono_gymassist.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnPanelRegister = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        chkMostrarContraseña = new javax.swing.JCheckBox();
        btnAtras = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        panelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setText("Email");
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("Contraseña");
        panelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(null);
        panelLogin.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 164, 256, -1));

        txtContraseña.setBackground(new java.awt.Color(255, 255, 255));
        txtContraseña.setBorder(null);
        panelLogin.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 256, 20));

        jLabel4.setText("No te has registrado?");
        panelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        btnPanelRegister.setText("registrarse");
        btnPanelRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelRegisterActionPerformed(evt);
            }
        });
        panelLogin.add(btnPanelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnIniciarSesion.setText("INICIAR SESION");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        panelLogin.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, 49));

        chkMostrarContraseña.setText("Mostrar contraseña");
        chkMostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMostrarContraseñaActionPerformed(evt);
            }
        });
        panelLogin.add(chkMostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtras.setText("Volver");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        panelLogin.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 110, 33));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_images/prueba3.jpg"))); // NOI18N
        panelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, -10, 330, 520));
        panelLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_images/Logo de PA sin fondo2.0.png"))); // NOI18N
        panelLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 80, 70));
        panelLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 270, 10));
        panelLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 270, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        MainScreen main_screen = new MainScreen ();
        main_screen.setVisible(true);
        this.setVisible(false);
        
    
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnPanelRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelRegisterActionPerformed
        RegisterScreen register_screen = new RegisterScreen();
        register_screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPanelRegisterActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
         // Verificar si se ha ingresado un correo y una contraseña
        if (!txtCorreo.getText().isEmpty() && !txtContraseña.getText().isEmpty()) {
            String correo = txtCorreo.getText();
            String contraseña = txtContraseña.getText();

            // Autenticar como cliente
            if (DatosLogic.autentificarCliente(correo, contraseña)) {
                JOptionPane.showMessageDialog(this, "Bienvenido como cliente");
                this.dispose(); // Cerrar el panel de inicio de sesión
                
                // Obtener el cliente actual
                PersonaModel usuarioActual = DatosController.getInstance().obtenerCliente(correo);
                
                // Abrir la ventana de cliente (UsuarioScreen) y pasar el usuario actual
                UsuarioScreen usuarioScreen = new UsuarioScreen(usuarioActual); //AQui, netbeans me recomienda cambiar dizquea UsuarioScreen(PersonaModel UsuarioActual)
                usuarioScreen.setVisible(true);
            }
            // Autenticar como administrador
            else if (DatosLogic.autentificarAdmin(correo, contraseña)) {
                JOptionPane.showMessageDialog(this, "Bienvenido como administrador");
                this.dispose(); // Cerrar el panel de inicio de sesión
                
                // Obtener el administrador actual
                AdministradorModel adminActual = DatosController.getInstance().obtenerAdmin(correo);
                
                // Abrir la ventana de administrador (AdminScreen) y pasar el administrador actual
                AdminScreen adminScreen = new AdminScreen(adminActual); //Aqui
                adminScreen.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o Contraseña incorrectos");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Falta ingresar el Usuario o Contraseña");
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void chkMostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarContraseñaActionPerformed
        if (chkMostrarContraseña.isSelected()){
            txtContraseña.setEchoChar((char)0);
        }else {
            txtContraseña.setEchoChar('*');
        }
    }//GEN-LAST:event_chkMostrarContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnPanelRegister;
    private javax.swing.JCheckBox chkMostrarContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
