/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;



import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logic.controller.DatosController;
import logic.controller.DatosLogic;
import logic.controller.GimnasioController;
import logic.model.AdministradorModel;
import logic.model.GimnasioModel;
import logic.model.PersonaModel;


public class RegisterScreen extends javax.swing.JFrame {
    
    /**
     * Creates new form RegisterScreen
     */
    public RegisterScreen() {
        initComponents();
        chkAdministrador.addActionListener(this::chkAdministradorActionPerformed);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Register Panel");
        this.setIconImage(new ImageIcon(getClass() .getResource("/icons_images/icono_gymassist.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbTipoID = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNoID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnFinRegistro = new javax.swing.JButton();
        chkAdministrador = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtNom_gym = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtvalor_mensual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRepContraseña = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setText("COMPLETE THE INFORMATION TO REGISTER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 59));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Nombre Completo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 779, 10));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 183, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Tipo de identificacion:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cbTipoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "CC", "TI", "RC" }));
        jPanel1.add(cbTipoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("N° Identificacion: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanel1.add(txtNoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 106, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Email: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 166, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setText("Contraseña: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 106, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setText("Usted es:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtras.setText("Back");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 87, 50));

        btnFinRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFinRegistro.setText("Register");
        btnFinRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 107, 50));

        chkAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkAdministrador.setText("Administrador de un gimnasio");
        chkAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAdministradorActionPerformed(evt);
            }
        });
        jPanel1.add(chkAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, 31));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Nombre del gimnasio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        txtNom_gym.setEditable(false);
        jPanel1.add(txtNom_gym, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 235, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setText("Valor Mensualidad del gimnasio:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        txtvalor_mensual.setEditable(false);
        jPanel1.add(txtvalor_mensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 100, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setText("Repetir contraseña: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        jPanel1.add(txtRepContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 106, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_images/Logo de PA sin fondo2.0.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, -1, 76));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_images/Gimnasios Register.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 810, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        MainScreen main_screen = new MainScreen();
        main_screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    
    private void chkAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAdministradorActionPerformed
        if (chkAdministrador.isSelected()) {
            // Si el checkBox está seleccionado (es un administrador), habilitar los campos
            txtNom_gym.setEditable(true);
            txtvalor_mensual.setEditable(true);
        } else {
            // Si el checkBox no está seleccionado (no es un administrador), deshabilitar los campos y limpiar su contenido
            txtNom_gym.setEditable(false);
            txtNom_gym.setText("");
            txtvalor_mensual.setEditable(false);
            txtvalor_mensual.setText("");
        }
    }//GEN-LAST:event_chkAdministradorActionPerformed

    private void btnFinRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinRegistroActionPerformed
    // Obtener los datos del formulario
    String nombre = txtNombre.getText();
    String tp_id = cbTipoID.getSelectedItem().toString();
    String no_id = txtNoID.getText();
    String correo = txtCorreo.getText();
    String contraseña = txtContraseña.getText();
    
    // Verificar que los campos de texto no estén vacíos antes de intentar convertirlos a enteros
    String nom_gym = txtNom_gym.getText().isEmpty() ? "" : txtNom_gym.getText();
    String val_mensual = txtvalor_mensual.getText().isEmpty() ? "" : txtvalor_mensual.getText();
    
    // Verificar si se está registrando un administrador
    boolean esAdmin = chkAdministrador.isSelected();
    int asistencias = 0;
    
    // Registrar el usuario utilizando DatosLogic
    if (DatosLogic.registrarUsuario(nombre, tp_id, no_id, correo, contraseña, esAdmin, nom_gym, val_mensual, asistencias)) {
        if (esAdmin) {
            // Crear un objeto AdministradorModel
            AdministradorModel admin = new AdministradorModel(true, nom_gym, val_mensual, nombre, tp_id, no_id, correo, contraseña, asistencias);
            // Obtener la instancia única de DatosController
            DatosController datosController = DatosController.getInstance();
            // Guardar el administrador en el archivo correspondiente
            datosController.guardarAdmin(admin);
            
            // Obtener la instancia existente de GimnasioController
            GimnasioController gimnasioController = GimnasioController.getInstance();
            // Insertar un nuevo gimnasio con lista de clientes vacía
            gimnasioController.insertarGimnasio(new GimnasioModel(nom_gym, val_mensual));
            // Guardar el gimnasio en el documento txt
            gimnasioController.guardarGimnasios();
            
            JOptionPane.showMessageDialog(null, "Administrador y gimnasio registrados exitosamente.");
        } else {
            // Crear un objeto PersonaModel
            PersonaModel cliente = new PersonaModel(nombre, tp_id, no_id, correo, contraseña, asistencias);
            // Obtener la instancia única de DatosController
            DatosController datosController = DatosController.getInstance();
            // Guardar el cliente en el archivo correspondiente
            datosController.insertarCliente(cliente);
            datosController.guardarCliente(cliente);
            System.out.println("Cliente insertado Correctamente"+ cliente);
            
            JOptionPane.showMessageDialog(null, "Cliente registrado exitosamente.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Error al registrar. Por favor, revise los datos.");
    }
    }//GEN-LAST:event_btnFinRegistroActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnFinRegistro;
    private javax.swing.JComboBox<String> cbTipoID;
    private javax.swing.JCheckBox chkAdministrador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNoID;
    private javax.swing.JTextField txtNom_gym;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtRepContraseña;
    private javax.swing.JTextField txtvalor_mensual;
    // End of variables declaration//GEN-END:variables
}
