
package pantallas;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import logic.controller.*;
import logic.model.GimnasioModel;
import logic.model.PersonaModel;
import pantallas.entrenamientos.*;

public class UsuarioScreen extends javax.swing.JFrame {
    private Espalda a;
    private Pecho b;
    private Pierna c;
    private Cardio d;
    private PersonaModel usuarioActual;
    
    
    
    private GimnasioController gimnasioController;
    /**
     * Creates new form UsuarioScreen
     */
    public UsuarioScreen(PersonaModel usuarioActual) {
        this.usuarioActual = usuarioActual;
    initComponents();
    this.setLocationRelativeTo(null);
    this.setResizable(false);
    this.setTitle("GYMASSIST TRAINING");
    this.setIconImage(new ImageIcon(getClass().getResource("/icons_images/icono_gymassist.png")).getImage());
    gimnasioController = GimnasioController.getInstance(); // Obtener la instancia existente
    cargarDatosGimnasios(gimnasioController);
     // Configurar la tabla para que no sea editable
jTableDatosGimnasios.setDefaultEditor(Object.class, null);

// Configurar el modo de selección a una sola selección
jTableDatosGimnasios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

// Añadir un MouseListener para seleccionar toda la fila al hacer clic
jTableDatosGimnasios.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        int filaSeleccionada = jTableDatosGimnasios.getSelectedRow();
        if (filaSeleccionada != -1) {
            jTableDatosGimnasios.setRowSelectionInterval(filaSeleccionada, filaSeleccionada); // Selecciona toda la fila

            // Asegurar que todas las celdas de la fila estén seleccionadas
            int columnas = jTableDatosGimnasios.getColumnCount();
            for (int i = 0; i < columnas; i++) {
                jTableDatosGimnasios.setColumnSelectionInterval(i, i);
            }
        }
    }
});
        

    }
    
    private void cargarDatosGimnasios(GimnasioController gimnasioController) { // Pasar gimnasioController como parámetro
        // Obtener la lista de gimnasios del controlador
    List<GimnasioModel> gimnasios = gimnasioController.obtenerGimnasios();

    // Agregar mensajes de depuración
    System.out.println("Total de gimnasios cargados: " + gimnasios.size());
    for (GimnasioModel gimnasio : gimnasios) {
        System.out.println("Gimnasio cargado: " + gimnasio);
    }

        // Obtener la lista de gimnasios del controlador
        

        // Crear un modelo de tabla
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Nombre Gim");
        modeloTabla.addColumn("Mensualidad");

        // Agregar los datos de los gimnasios al modelo de tabla
        for (GimnasioModel gimnasio : gimnasios) {
            Object[] fila = {gimnasio.getNom_gym(), gimnasio.getVal_mensual()};
            modeloTabla.addRow(fila);
        }

        // Asignar el modelo de tabla a la tabla jTableDatosGimnasios
        jTableDatosGimnasios.setModel(modeloTabla);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNombreCliente = new javax.swing.JLabel();
        imagen_espalda = new javax.swing.JLabel();
        imagen_pecho = new javax.swing.JLabel();
        imagen_pierna = new javax.swing.JLabel();
        imagen_cardio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatosGimnasios = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        btnInscribirGim = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), java.awt.Color.gray));

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GYMASSIST TRAINING");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel2.setText("BIENVENIDO SEÑOR(A)");

        labelNombreCliente.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelNombreCliente.setText("Nombre_Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNombreCliente)
                        .addGap(139, 139, 139))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNombreCliente)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imagen_espalda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_images/imagen_espalda.png"))); // NOI18N
        imagen_espalda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        imagen_espalda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imagen_espaldaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imagen_espaldaMouseExited(evt);
            }
        });
        jPanel1.add(imagen_espalda, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 159, -1, -1));

        imagen_pecho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_images/pecho_imagen.jpg"))); // NOI18N
        imagen_pecho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        imagen_pecho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imagen_pechoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imagen_pechoMouseExited(evt);
            }
        });
        jPanel1.add(imagen_pecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 304, -1, 90));

        imagen_pierna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_images/pierna_imagen.png"))); // NOI18N
        imagen_pierna.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        imagen_pierna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imagen_piernaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imagen_piernaMouseExited(evt);
            }
        });
        jPanel1.add(imagen_pierna, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 159, -1, 90));

        imagen_cardio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_images/cardio_imagen.jpg"))); // NOI18N
        imagen_cardio.setText("jLabel3");
        imagen_cardio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        imagen_cardio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imagen_cardioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imagen_cardioMouseExited(evt);
            }
        });
        jPanel1.add(imagen_cardio, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 304, 154, 90));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel4.setText("ENTRAMIENTO ESPALDA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 139, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel5.setText("ENTRAMIENTO PECHO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 284, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel6.setText("ENTRAMIENTO PIERNA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 139, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel7.setText("CARDIO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 284, -1, -1));

        jTableDatosGimnasios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NombreGym", "Valor Mensual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDatosGimnasios.getTableHeader().setResizingAllowed(false);
        jTableDatosGimnasios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableDatosGimnasios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 183, 186, 92));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 155, 186, -1));

        btnInscribirGim.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnInscribirGim.setText("Inscribirme en el Gimnasio");
        btnInscribirGim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirGimActionPerformed(evt);
            }
        });
        jPanel1.add(btnInscribirGim, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 304, -1, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("GIMNASIO INSCRITO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 139, -1, -1));

        jTextField2.setEditable(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 164, 102, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("DIAS DE MENSUALIDAD FALTANTES");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 192, -1, -1));

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 217, 105, -1));

        jButton2.setText("Registrar Asistencia");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 304, -1, 38));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("ASISTENCIAS ACTUALES");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 251, -1, -1));

        jTextField4.setEditable(false);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 276, 95, -1));

        jButton3.setText(" RENOVAR MENSUALIDAD");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 348, -1, 43));

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_images/icon_perfil.png"))); // NOI18N

        MenuItemCerrarSesion.setText("Cerrar Sesion");
        MenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemCerrarSesion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imagen_espaldaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen_espaldaMouseEntered
        a = new Espalda();
        a.setVisible(true);
    }//GEN-LAST:event_imagen_espaldaMouseEntered

    private void imagen_espaldaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen_espaldaMouseExited
        if (a != null){
            a.setVisible(false);
        }
    }//GEN-LAST:event_imagen_espaldaMouseExited

    private void imagen_pechoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen_pechoMouseEntered
        b = new Pecho();
        b.setVisible(true);
    }//GEN-LAST:event_imagen_pechoMouseEntered

    private void imagen_pechoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen_pechoMouseExited
        if (b != null){
            b.setVisible(false);
        }
    }//GEN-LAST:event_imagen_pechoMouseExited

    private void imagen_piernaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen_piernaMouseEntered
        c = new Pierna();
        c.setVisible(true);
    }//GEN-LAST:event_imagen_piernaMouseEntered

    private void imagen_piernaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen_piernaMouseExited
        if (c != null){
            c.setVisible(false);
        }
    }//GEN-LAST:event_imagen_piernaMouseExited

    private void imagen_cardioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen_cardioMouseEntered
        d = new Cardio();
        d.setVisible(true);
    }//GEN-LAST:event_imagen_cardioMouseEntered

    private void imagen_cardioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagen_cardioMouseExited
        if (d != null){
            d.setVisible(false);
        }
    }//GEN-LAST:event_imagen_cardioMouseExited

    private void MenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCerrarSesionActionPerformed
        MainScreen pantalla_principal = new MainScreen();
        pantalla_principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuItemCerrarSesionActionPerformed

    private void btnInscribirGimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirGimActionPerformed
        // Verificar si usuarioActual está correctamente inicializado
    if (usuarioActual == null) {
        JOptionPane.showMessageDialog(this, "Error: El usuario no está correctamente inicializado.");
        return; // Salir del método si usuarioActual es null
    }

    // Verificar si el cliente ya está registrado en algún gimnasio
    for (GimnasioModel gimnasio : gimnasioController.obtenerGimnasios()) {
        if (gimnasio.getClientes_gimnasio().contains(usuarioActual.getNombre())) {
            JOptionPane.showMessageDialog(this, "Ya estás registrado en el gimnasio " + gimnasio.getNom_gym() + ".");
            return; // Salir del método si ya está registrado
        }
    }

    // Obtener el índice de la fila seleccionada en la tabla
    int filaSeleccionada = jTableDatosGimnasios.getSelectedRow();

    // Verificar si se seleccionó alguna fila
    if (filaSeleccionada != -1) {
        // Obtener el nombre del gimnasio seleccionado en esa fila
        String nombreGym = (String) jTableDatosGimnasios.getValueAt(filaSeleccionada, 0);

        // Guardar la inscripción del cliente en el gimnasio
        gimnasioController.guardarInscripcionGimnasio(nombreGym, usuarioActual.getNombre());

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "¡Inscripción exitosa en " + nombreGym + "!");
    } else {
        JOptionPane.showMessageDialog(this, "Error: Debes seleccionar un gimnasio.");
    }
    }//GEN-LAST:event_btnInscribirGimActionPerformed
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemCerrarSesion;
    private javax.swing.JButton btnInscribirGim;
    private javax.swing.JLabel imagen_cardio;
    private javax.swing.JLabel imagen_espalda;
    private javax.swing.JLabel imagen_pecho;
    private javax.swing.JLabel imagen_pierna;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatosGimnasios;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel labelNombreCliente;
    // End of variables declaration//GEN-END:variables
}
